<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_usage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_usage module.
    case 'help.page.entity_usage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Enhances each entity with a list of entities that reference it.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function entity_usage_entity_type_alter(array &$entity_types) {
  $types = \Drupal::config('entity_usage.settings')->get('entity_types');

  if (!empty($types)) {
    foreach ($types as $type => $enabled) {
      if (isset($entity_types[$type]) && $enabled) {
        $entity_types[$type]->setLinkTemplate('entity-usage', "/entity_usage/$type/{{$type}}");
      }
    }
  }
}

// TODO Add 'access entity usage information' permission.
// TODO Verify that tab shows up on media pages.
// TODO Write tests.
